# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://JinyongJeong.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             http://JinyongJeong.github.io


title:               Jinyong

# Pagination
paginate:            2
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
   This blog is to remember what I studied.
# The tags listed as entries in the sidebar
sidebar_tags:        [post, SLAM, ubuntu, software, android, ios, jekyll, math, IRAP]

# Fallback image and color if not overwritten for tag or post
image:                /public/img/3.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Jinyong Jeong'

  # This photo will be used in the about section
  photo:             /images/about/profile.jpg
  photo2x:           /images/about/profile.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |

    ### Jinyong Jeong

    E-mail: jjy0923@kaist.ac.kr, jjy0923@gmail.com

    Instagram: Jinyongjeong_steve

    Facebook: Jinyong Jeong Steve
    
    Dataset Homepage: [http://irap.kaist.ac.kr/dataset](http://irap.kaist.ac.kr/dataset)
    
   
    [<My 3D model>](http://irap.kaist.ac.kr/dataset/webgl_person/jjeong/jjeong.html)

    [Current]

    * ph.D student
    * Civil and Environmental Engineering(CEE)
    * Korea Advanced Institute of Science and Technology([KAIST](http://www.kaist.ac.kr))
    * Intelligent Robotic Autonomy and Perception([IRAP](http://irap.kaist.ac.kr))
    * Research Interest: Autonomous car, SLAM, computer Vision

    [Previous]

    * 2005.02 ~ 2012.08 : Inha university (undergraduate course)
    * 2012.08 ~ 2014.08 : KAIST (master course)
    * 2014.08 ~ 2015.10 : Defense Agency for Technology and Quality (DTaQ) researcher
    * 2016.02 ~ current : KAIST (ph.D course)

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    facebook:        jinyong.jeong.399
    youtube:         UCPuPw9OXrBzYue3Sv4uvVxQ
    github:          JinyongJeong
    # twitter:         _username_
    # google:          _number_
    # vk:              _username_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-92196026-1'

# Setting a disqus subdomain will enable the comment section
disqus:            jinyongjeong

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
